name: Action ğŸ² # 1

on:
  push:
    branches:
      - main
      - develop

jobs:
  Action:
    name: Action ğŸ²
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘Ÿ Start
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: âšª Checkout repo
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ“€ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: ğŸ Finish (1)
        env: # Or as an environment variable
          MY_NAME: ${{ secrets.MY_NAME }}
        run: |
          echo "ğŸ This job's status is ${{ job.status }}. Congrats you are good to go $MY_NAME"
