name: Build ğŸ“¦ # 2

# pull_request:
on:
  push:
		paths:
			- '**.html'
			- '**.js'
			- '**.jsx'
		paths-ignore:
			- '**.md'
			- '**.mdx'
			- '**.yml'
			- '**.yaml'
    branches:
			- main
			- develop

jobs:
  Build:
    name: Build ğŸ“¦
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: âšª Checkout repo
  			uses: actions/checkout@v3
      - name: ğŸŸ¢ Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: ğŸ‘Ÿ Start
        run: npm ci
        run: npm run build --if-present
      - name: ğŸ Finish (2)
