name: Test ğŸ§ª # 3

on:
  push:
    branches:
    - main
    - develop

jobs:
  Test:
    name: Test ğŸ§ª
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: âšª Checkout repo
        uses: actions/checkout@v2
      - name: ğŸŸ¢ Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Start ğŸ‘Ÿ
        run: yarn ci
        run: yarn test --if-present
      - name: Finish ğŸ (3)
        run: echo "done"
