name: Test ğŸ§ª # 3

# pull_request:
on:
  push:
    branches:
      - main
      - develop
  # allows manual run workflow in action tab
  workflow_dipatch:
    # paths:
    #   - '**.html'
    #   - '**.js'
    #   - '**.jsx'
    # paths-ignore:
    #   - '**.md'
    #   - '**.mdx'
    #   - '**.yml'
    #   - '**.yaml'

jobs:
  Test:
    name: Test ğŸ§ª
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: âšª Checkout repo
        uses: actions/checkout@v3
      - name: ğŸŸ¢ Setup node ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        uses: actions/setup-node@v2
      - name: ğŸ‘Ÿ Start
        run: npm ci
        run: npm run test --if-present
      - name: ğŸ Finish (3)
